steps:
# Step 1: Build the Docker image
# This step uses the 'docker' builder to build the image based on your Dockerfile.
# The image is tagged with the project ID and a service name.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/svaraflow/auramart-prototype', '.']

# Step 2: Push the built image to Google Container Registry
# The 'docker' builder is used again to push the tagged image to the registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/svaraflow/auramart-prototype']

# Step 3: Deploy the image to Cloud Run
# This step uses the 'gcloud' builder to deploy the image to Cloud Run.
# The --platform managed and --region flags are important for a managed Cloud Run service.
# The --allow-unauthenticated flag makes your service publicly available.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'auramart-prototype', '--image', 'gcr.io/svaraflow/auramart-prototype', '--platform', 'managed', '--region', 'asia-south1', '--allow-unauthenticated']
  env:
  - 'CLOUDRUN_SERVICE_NAME=auramart-prototype'